version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: go_app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    ports:
      - "8080:8080"  # Expose Go app port 8080 to host 8080
    restart: on-failure

volumes:
  mongodb_data:
